# Generated by Django 5.2.6 on 2025-09-25 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250922_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='posts.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='description',
            field=models.CharField(help_text='Write a description about the status: ', max_length=256),
        ),
    ]
